package Examen1P2_LloydCooper;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class frameMain extends javax.swing.JFrame {

    private ArrayList <Equipo> equipos = new ArrayList();
    private ArrayList <Estadio> estadios = new ArrayList();
    private ArrayList <Jugador> jugadores = new ArrayList();
    
    public frameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCrearEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombreEquipo = new javax.swing.JTextField();
        tfPaisEquipo = new javax.swing.JTextField();
        btnCrearEquipo = new javax.swing.JButton();
        panelModificarJugador = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfNuevoNombreEquipo = new javax.swing.JTextField();
        tfNuevoPaisEquipo = new javax.swing.JTextField();
        comboBoxModificarEquipo = new javax.swing.JComboBox<>();
        btnModificarEquipo = new javax.swing.JButton();
        panelListarEquipo = new javax.swing.JPanel();
        panelEliminarEquipo = new javax.swing.JPanel();
        panelCrearEstadio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNombreEstadio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCiudadEstadio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCapacidadEstadio = new javax.swing.JTextField();
        comboBoxEquipos = new javax.swing.JComboBox<>();
        btnCrearEstadio = new javax.swing.JButton();
        panelModificarEstadio = new javax.swing.JPanel();
        panelListarEstadio = new javax.swing.JPanel();
        panelEliminarEstadio = new javax.swing.JPanel();
        panelCrearJugador = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfNombreJugador = new javax.swing.JTextField();
        tfEdadJugador = new javax.swing.JTextField();
        tfNacionalidadJugador = new javax.swing.JTextField();
        tfPieHabilJugador = new javax.swing.JTextField();
        comboBoxEquipoJugador = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCrearJugador = new javax.swing.JButton();
        paneModificarJugador = new javax.swing.JPanel();
        panelListarJugador = new javax.swing.JPanel();
        panelEliminarJugador = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCrearEquipo.setBackground(new java.awt.Color(255, 255, 255));
        panelCrearEquipo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre del equipo");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pais del equipo");

        btnCrearEquipo.setText("Crear equipo");
        btnCrearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearEquipoLayout = new javax.swing.GroupLayout(panelCrearEquipo);
        panelCrearEquipo.setLayout(panelCrearEquipoLayout);
        panelCrearEquipoLayout.setHorizontalGroup(
            panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearEquipoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCrearEquipoLayout.createSequentialGroup()
                        .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPaisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelCrearEquipoLayout.setVerticalGroup(
            panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearEquipoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPaisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnCrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear equipo", panelCrearEquipo);

        panelModificarJugador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nuevo nombre del equipo");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nuevo pais del equipo");

        btnModificarEquipo.setText("Modificar equipo");
        btnModificarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelModificarJugadorLayout = new javax.swing.GroupLayout(panelModificarJugador);
        panelModificarJugador.setLayout(panelModificarJugadorLayout);
        panelModificarJugadorLayout.setHorizontalGroup(
            panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarJugadorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboBoxModificarEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelModificarJugadorLayout.createSequentialGroup()
                            .addGroup(panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfNuevoNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNuevoPaisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnModificarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelModificarJugadorLayout.setVerticalGroup(
            panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarJugadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(comboBoxModificarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNuevoNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNuevoPaisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(btnModificarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar equipo", panelModificarJugador);

        javax.swing.GroupLayout panelListarEquipoLayout = new javax.swing.GroupLayout(panelListarEquipo);
        panelListarEquipo.setLayout(panelListarEquipoLayout);
        panelListarEquipoLayout.setHorizontalGroup(
            panelListarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelListarEquipoLayout.setVerticalGroup(
            panelListarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar equipo", panelListarEquipo);

        javax.swing.GroupLayout panelEliminarEquipoLayout = new javax.swing.GroupLayout(panelEliminarEquipo);
        panelEliminarEquipo.setLayout(panelEliminarEquipoLayout);
        panelEliminarEquipoLayout.setHorizontalGroup(
            panelEliminarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelEliminarEquipoLayout.setVerticalGroup(
            panelEliminarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar equipo", panelEliminarEquipo);

        panelCrearEstadio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del estadio");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ciudad del estadio");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Capacidad del estadio");

        comboBoxEquipos.setSelectedIndex(-1);

        btnCrearEstadio.setText("Crear estadio");
        btnCrearEstadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearEstadioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearEstadioLayout = new javax.swing.GroupLayout(panelCrearEstadio);
        panelCrearEstadio.setLayout(panelCrearEstadioLayout);
        panelCrearEstadioLayout.setHorizontalGroup(
            panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearEstadioLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelCrearEstadioLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCapacidadEstadio))
                        .addGroup(panelCrearEstadioLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(tfCiudadEstadio))
                        .addGroup(panelCrearEstadioLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfNombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCrearEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelCrearEstadioLayout.setVerticalGroup(
            panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearEstadioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCiudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCapacidadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear estadio", panelCrearEstadio);

        javax.swing.GroupLayout panelModificarEstadioLayout = new javax.swing.GroupLayout(panelModificarEstadio);
        panelModificarEstadio.setLayout(panelModificarEstadioLayout);
        panelModificarEstadioLayout.setHorizontalGroup(
            panelModificarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelModificarEstadioLayout.setVerticalGroup(
            panelModificarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar estadio", panelModificarEstadio);

        javax.swing.GroupLayout panelListarEstadioLayout = new javax.swing.GroupLayout(panelListarEstadio);
        panelListarEstadio.setLayout(panelListarEstadioLayout);
        panelListarEstadioLayout.setHorizontalGroup(
            panelListarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelListarEstadioLayout.setVerticalGroup(
            panelListarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar estadio", panelListarEstadio);

        javax.swing.GroupLayout panelEliminarEstadioLayout = new javax.swing.GroupLayout(panelEliminarEstadio);
        panelEliminarEstadio.setLayout(panelEliminarEstadioLayout);
        panelEliminarEstadioLayout.setHorizontalGroup(
            panelEliminarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelEliminarEstadioLayout.setVerticalGroup(
            panelEliminarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar estadio", panelEliminarEstadio);

        panelCrearJugador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre del jugador");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Edad del jugador");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nacionalidad del jugador");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Pie habil del jugador");

        btnCrearJugador.setText("Crear jugador");
        btnCrearJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearJugadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCrearJugadorLayout = new javax.swing.GroupLayout(panelCrearJugador);
        panelCrearJugador.setLayout(panelCrearJugadorLayout);
        panelCrearJugadorLayout.setHorizontalGroup(
            panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearJugadorLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboBoxEquipoJugador, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCrearJugadorLayout.createSequentialGroup()
                        .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearJugadorLayout.createSequentialGroup()
                                .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18))
                            .addGroup(panelCrearJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(43, 43, 43)))
                        .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPieHabilJugador)
                            .addComponent(tfNombreJugador)
                            .addComponent(tfEdadJugador)
                            .addComponent(tfNacionalidadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addComponent(btnCrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelCrearJugadorLayout.setVerticalGroup(
            panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearJugadorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearJugadorLayout.createSequentialGroup()
                        .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEdadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNacionalidadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panelCrearJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPieHabilJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxEquipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCrearJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear jugador", panelCrearJugador);

        javax.swing.GroupLayout paneModificarJugadorLayout = new javax.swing.GroupLayout(paneModificarJugador);
        paneModificarJugador.setLayout(paneModificarJugadorLayout);
        paneModificarJugadorLayout.setHorizontalGroup(
            paneModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        paneModificarJugadorLayout.setVerticalGroup(
            paneModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar jugador", paneModificarJugador);

        javax.swing.GroupLayout panelListarJugadorLayout = new javax.swing.GroupLayout(panelListarJugador);
        panelListarJugador.setLayout(panelListarJugadorLayout);
        panelListarJugadorLayout.setHorizontalGroup(
            panelListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelListarJugadorLayout.setVerticalGroup(
            panelListarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar jugador", panelListarJugador);

        javax.swing.GroupLayout panelEliminarJugadorLayout = new javax.swing.GroupLayout(panelEliminarJugador);
        panelEliminarJugador.setLayout(panelEliminarJugadorLayout);
        panelEliminarJugadorLayout.setHorizontalGroup(
            panelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        panelEliminarJugadorLayout.setVerticalGroup(
            panelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar jugador", panelEliminarJugador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEquipoMouseClicked
              
        if (tfNombreEquipo.getText().equals("") || tfPaisEquipo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
        } else {
            String nombreEquipo = tfNombreEquipo.getText();
            String paisEquipo = tfPaisEquipo.getText();

            equipos.add(new Equipo(nombreEquipo, paisEquipo));
            tfNombreEquipo.setText("");
            tfPaisEquipo.setText("");
            
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) comboBoxEquipos.getModel();
            DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) comboBoxEquipoJugador.getModel();
            
            for (Equipo equipo : equipos) {
                modelo.addElement(equipo);
            }
            for (Equipo equipo : equipos) {
                modelo1.addElement(equipo);
            }
            comboBoxEquipos.setModel(modelo);
            comboBoxEquipoJugador.setModel(modelo1);

            JOptionPane.showMessageDialog(this, "Equipo creado correctamente");     
        }   
    }//GEN-LAST:event_btnCrearEquipoMouseClicked

    private void btnCrearEstadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearEstadioMouseClicked
        
        if (tfNombreEstadio.getText().equals("") || tfCiudadEstadio.getText().equals("") 
                || tfCapacidadEstadio.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
        } else {
            String nombreEquipo = tfNombreEstadio.getText();
            String paisEquipo = tfCiudadEstadio.getText();
            int capacidadEquipo = Integer.parseInt(tfCapacidadEstadio.getText());
            Equipo equipo = equipos.get(comboBoxEquipos.getSelectedIndex()); 
            
            estadios.add(new Estadio(nombreEquipo, paisEquipo, capacidadEquipo, equipo));
            
            tfNombreEstadio.setText("");
            tfCiudadEstadio.setText("");
            tfCapacidadEstadio.setText("");
            
            JOptionPane.showMessageDialog(this, "Estadio creado correctamente");     
        } 
    }//GEN-LAST:event_btnCrearEstadioMouseClicked

    private void btnCrearJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearJugadorMouseClicked
        if (tfNombreJugador.getText().equals("") || tfEdadJugador.getText().equals("") 
            || tfNacionalidadJugador.getText().equals("") || tfPieHabilJugador.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            
        } else {
            String nombreJugador = tfNombreJugador.getText();
            int edadJugador = Integer.parseInt(tfEdadJugador.getText());
            String nacionalidadJugador = tfNacionalidadJugador.getText();
            String pieHabilJugador = tfPieHabilJugador.getText();
            Equipo equipo = equipos.get(comboBoxEquipoJugador.getSelectedIndex()); 
            
            jugadores.add(new Jugador(nombreJugador, edadJugador, nacionalidadJugador, pieHabilJugador, equipo));
            
            tfNombreJugador.setText("");
            tfEdadJugador.setText("");
            tfNacionalidadJugador.setText("");
            tfPieHabilJugador.setText("");
            
            JOptionPane.showMessageDialog(this, "Jugador creado correctamente");     
        } 
    }//GEN-LAST:event_btnCrearJugadorMouseClicked

    private void btnModificarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarEquipoMouseClicked
        
    }//GEN-LAST:event_btnModificarEquipoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearEquipo;
    private javax.swing.JButton btnCrearEstadio;
    private javax.swing.JButton btnCrearJugador;
    private javax.swing.JButton btnModificarEquipo;
    private javax.swing.JComboBox<String> comboBoxEquipoJugador;
    private javax.swing.JComboBox<String> comboBoxEquipos;
    private javax.swing.JComboBox<String> comboBoxModificarEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel paneModificarJugador;
    private javax.swing.JPanel panelCrearEquipo;
    private javax.swing.JPanel panelCrearEstadio;
    private javax.swing.JPanel panelCrearJugador;
    private javax.swing.JPanel panelEliminarEquipo;
    private javax.swing.JPanel panelEliminarEstadio;
    private javax.swing.JPanel panelEliminarJugador;
    private javax.swing.JPanel panelListarEquipo;
    private javax.swing.JPanel panelListarEstadio;
    private javax.swing.JPanel panelListarJugador;
    private javax.swing.JPanel panelModificarEstadio;
    private javax.swing.JPanel panelModificarJugador;
    private javax.swing.JTextField tfCapacidadEstadio;
    private javax.swing.JTextField tfCiudadEstadio;
    private javax.swing.JTextField tfEdadJugador;
    private javax.swing.JTextField tfNacionalidadJugador;
    private javax.swing.JTextField tfNombreEquipo;
    private javax.swing.JTextField tfNombreEstadio;
    private javax.swing.JTextField tfNombreJugador;
    private javax.swing.JTextField tfNuevoNombreEquipo;
    private javax.swing.JTextField tfNuevoPaisEquipo;
    private javax.swing.JTextField tfPaisEquipo;
    private javax.swing.JTextField tfPieHabilJugador;
    // End of variables declaration//GEN-END:variables
}
